[package]
name = "deltime"
version = "0.1.0"
edition = "2021"

[dependencies]

utilites = {git = "https://github.com/P40b0s/help_utilites.git", package = "utilites", default-features = false, features = ["dates", "retry"]}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
clap= {version = "4.5.7", features = ["derive"]}
clap_derive="4.5.4"
indicatif= {version = "0.17.9", git = "https://github.com/console-rs/indicatif.git"}
[dev-dependencies]
logger = {git = "https://github.com/P40b0s/logger.git"}