[package]
name = "deltime"
version = "0.1.0"
edition = "2021"

[dependencies]

utilites = {git = "https://github.com/P40b0s/help_utilites.git", package = "utilites", default-features = false, features = ["dates", "retry"]}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
clap= {version = "4.5.7", features = ["derive"]}
clap_derive="4.5.4"
indicatif= {version = "0.17.9", git = "https://github.com/console-rs/indicatif.git"}
usbenum="*"
mountpoints="*"
thiserror="*"
tokio= {version = "1.41.1", features = ["macros", "rt", "rt-multi-thread", "bytes"] }
logger = {git = "https://github.com/P40b0s/logger.git"}
async-channel="2.3.1"
futures="0.3.31"
[target.'cfg(target_os = "linux")'.dependencies]
udev="0.9.3"
[target.'cfg(target_os = "windows")'.dependencies]
wmi="0.15.0"





[dev-dependencies]
