[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/1"
interval = 1
repeat = "once"
visible = true

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/2"
date = "2025-02-14T16:12:12"
repeat = "once"
visible = true

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/3"
date = "2025-02-14T16:15:12"
repeat = "once"
visible = true

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/4"
date = "2025-02-14T16:12:12"
repeat = "dialy"
visible = false

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/5"
mask = "*.delme"
interval = 1
repeat = "forever"
visible = true

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/not_exists"
interval = 1
repeat = "monthly"
visible = true

[[tasks]]
path = "/hard/xar/projects/rust/deltime/tests/expired"
date = "2025-02-14T16:06:12"
repeat = "once"
visible = true
