[[tasks]]
file_path = "/hard/xar/projects/tests/1"
del_time_interval = 2
repeat = "once"
visible = true

[[tasks]]
file_path = "/hard/xar/projects/tests/2"
del_time = "2025-02-04T17:51:42"
repeat = "once"
visible = true

[[tasks]]
file_path = "/hard/xar/projects/tests/3"
del_time = "2025-02-04T17:54:42"
repeat = "once"
visible = true

[[tasks]]
file_path = "/hard/xar/projects/tests/4"
del_time_interval = 2
repeat = "dialy"
visible = false

[[tasks]]
file_path = "/hard/xar/projects/tests/5"
del_time_interval = 1
repeat = "monthly"
visible = true

[[tasks]]
file_path = "/hard/xar/projects/tests/not_exists"
del_time_interval = 1
repeat = "monthly"
visible = true
