[[tasks]]
path = "/home/phobos/projects/rust/deltime/tests/usb_1"
interval = 2
repeat = "once"
visible = true

[[tasks]]
path = "/home/phobos/projects/rust/deltime/tests/usb_2"
date = "2025-02-15T21:15:54"
repeat = "once"
visible = true

[[tasks]]
path = "/home/phobos/projects/rust/deltime/tests/usb_3"
date = "2025-02-15T21:18:54"
repeat = "once"
visible = true

[[tasks]]
path = "/home/phobos/projects/rust/deltime/tests/usb_4"
date = "2025-02-15T21:15:54"
repeat = "dialy"
visible = false
